name: Build and Test Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: # Build every day at 5PM UTC
    - cron: '0 17 * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -C instrument-coverage
  LLVM_PROFILE_FILE: meshchat-%p-%m.profraw
  RUST_BACKTRACE: 1
  GH_TOKEN: ${{ github.token }}

jobs:
  build-and-test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-11-arm ]
        #########Testing
        #os: [ ubuntu-latest, windows-latest, macos-15, windows-11-arm, ubuntu-24.04-arm ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: Install grcov
        if: runner.os != 'Windows'
        run: cargo install grcov

      - name: Setup LCOV
        if: runner.os != 'Windows'
        uses: hrishikesh-kadam/setup-lcov@v1
        with:
          ref: HEAD

      - name: Install dependencies - Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install libdbus-1-dev pkg-config

      #########Testing
      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1

      - name: Cache WiX v3
        if: runner.os == 'Windows'
        id: cache-wix
        uses: actions/cache@v4
        with:
          path: ~/.wix/bin
          key: wix-3.11.2

      - name: Install WiX v3
        if: runner.os == 'Windows' && steps.cache-wix.outputs.cache-hit != 'true'
        run: |
          curl -LO https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
          Expand-Archive wix311-binaries.zip -DestinationPath "$env:USERPROFILE\.wix\bin"

      - name: Add WiX to PATH
        if: runner.os == 'Windows'
        run: echo "$env:USERPROFILE\.wix\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Install cargo wix for Windows
        if: runner.os == 'Windows'
        run: cargo install cargo-wix

      - name: Run cargo wix on Windows
        if: runner.os == 'Windows'
        run: cargo wix --verbose --nocapture
      #########Testing

      - name: debug build
        run: cargo build

      - name: Publish dry-run
        run: cargo build --release && cargo publish --dry-run --allow-dirty --no-verify

      - name: test - non-Linux
        if: runner.os != 'Linux'
        run: cargo test

      - name: test - Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install weston
          weston -Bheadless -Sweston &
          sudo apt install libdbus-1-dev pkg-config
          cargo test
        env:
          WAYLAND_DISPLAY: weston

      - name: Clean up coverage
        if: runner.os != 'Windows'
        run: |
          grcov . --binary-path target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" --ignore "**/test_helper.rs" --ignore "**/icons.rs" --ignore "**/styles.rs" -o lcov.info
          lcov --remove lcov.info 'target/debug/build/**' 'target/release/build/**' '/usr*' '**/errors.rs' \
          '**/build.rs' '*tests/*' '**/test_helper.rs' '**/icons.rs' '**/styles.rs' --ignore-errors unused,unused --ignore-errors unsupported --ignore-errors \
          inconsistent --ignore-errors empty,empty -o lcov.info --erase-functions "(?=^.*fmt).+" --erase-functions "(?=^.*tests::).+"

      - name: UploadCoverage
        if: runner.os != 'Windows'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          verbose: true
